name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se activa cada vez que ocurre el push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/portfolio/browser # La carpeta que genera angular
          branch: gh-pages # La rama donde se guardará el sitio compilado